### ISSUE TITLE
Filter not working 

### ISSUE THREAD

**Issue by ValdesChe** [Sanix-Darker/zolo#10]
When you try set provider filter (GITHUB, GITLAB, BITBUCKET) before searching it doesn't show the repository corresponding to the filter. It always show GITHUB repos. 
And sometimes you got an error log in console saying "Cannot read property 'map' of undefined" due to error while fetching result from bitbucket
![DeepinScreenshot_20201015052828](https://user-images.githubusercontent.com/22135357/96069920-7a565800-0e9f-11eb-9ca0-d673c6c37180.png)
![DeepinScreenshot_20201015053341](https://user-images.githubusercontent.com/22135357/96070031-ae317d80-0e9f-11eb-91f6-c3fa85dcfe11.png)

**Comment by Sanix-Darker** [comment]
Thanks for this report, will be fix ASAP !
