### ISSUE TITLE
Website not responsive on some screen sizes

### ISSUE THREAD

**Issue by DTan13** [Sanix-Darker/zolo#5]
![Screenshot_2020-09-18 Zolo-Search-Engine App(1)](https://user-images.githubusercontent.com/48372719/93587620-cf4d9e00-f9c7-11ea-8ac5-72f7e6db56b4.png)
![Screenshot from 2020-09-18 15-56-16](https://user-images.githubusercontent.com/48372719/93587754-fd32e280-f9c7-11ea-8a71-d2180839e50e.png)

**Comment by Sanix-Darker** [comment]
Hi, thanks for the contribution with this !
Am closing this issue then !
